image:
  - Ubuntu

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

branches:
  only:
    - master
    - develop
    - /release\/.*/
    - /hotfix\/.*/
    - /feature\/.*/

test: off
build: off

build_script:
  - sh: ./build.sh --target=CI

cache:
  - "tools -> recipe.cake,.config/dotnet-tools.json"
